### ISSUE TITLE
Cannot install from Docker or regular way

### ISSUE THREAD

**Issue by kaatt** [Den1al/JSShell#24]
Running `./scripts/start_docker_shell.sh` fails:

```
running JSShell 2.0 CLI ...
db not exists, creating it...
jsshell-master_db_1 is up-to-date
web API not exists, creating it...
Building web
Step 1/9 : FROM python:3.6-jessie
 ---> 890456b21ed5
Step 2/9 : RUN apt-get update
 ---> Using cache
 ---> 266133288743
Step 3/9 : RUN apt-get install software-properties-common less vim -y
 ---> Using cache
 ---> 2d8c3877cd63
Step 4/9 : ENV INSTALL_PATH /app/
 ---> Using cache
 ---> e288e0d6ca01
Step 5/9 : RUN mkdir -p $INSTALL_PATH
 ---> Using cache
 ---> 612d2c5e43bc
Step 6/9 : WORKDIR $INSTALL_PATH
 ---> Using cache
 ---> 2d3a57cbf551
Step 7/9 : COPY requirements.txt requirements.txt
 ---> Using cache
 ---> 7cec26c3660a
Step 8/9 : RUN pip install -r requirements.txt
 ---> Using cache
 ---> 433715145f67
Step 9/9 : COPY . .
 ---> Using cache
 ---> 5d2006eaa508
Successfully built 5d2006eaa508
Successfully tagged jsshell-master_web:latest
jsshell-master_db_1 is up-to-date
Starting jsshell-master_web_1 ... error

ERROR: for jsshell-master_web_1  Cannot start service web: b'Mounts denied: \r\nThe path /etc/letsencrypt\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'

ERROR: for web  Cannot start service web: b'Mounts denied: \r\nThe path /etc/letsencrypt\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'
ERROR: Encountered errors while bringing up the project.
Starting jsshell-master_db_1 ... done
Starting jsshell-master_web_1 ... error

ERROR: for jsshell-master_web_1  Cannot start service web: b'Mounts denied: \r\nThe path /etc/letsencrypt\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'

ERROR: for web  Cannot start service web: b'Mounts denied: \r\nThe path /etc/letsencrypt\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'
ERROR: Encountered errors while bringing up the project.
```

Running `python manage.py web` fails too:
```

 * Serving Flask app "web" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    ).get(args.mode)()
  File "manage.py", line 9, in handle_web
    start_api_server()
  File "/Users/kaatt/Downloads/JSShell-master/web/__init__.py", line 36, in start_api_server
    lets_encrypt_base_path + 'privkey.pem'
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/serving.py", line 1009, in run_simple
    inner()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/serving.py", line 962, in inner
    fd=fd,
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/serving.py", line 805, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/serving.py", line 723, in __init__
    self.socket = ssl_context.wrap_socket(sock, server_side=True)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/serving.py", line 611, in wrap_socket
    **kwargs
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1232, in wrap_socket
    context.load_cert_chain(certfile, keyfile)
FileNotFoundError: [Errno 2] No such file or directory
```

Really want to use this. Can you help troubleshoot what's the issue here?

**Comment by Den1al** [comment]
You are running JSShell with letsencrypt option. What the framework is doing, is looking for the certificates on your host (look at the `docker-compose.yml` file). Either you didn't create them (you can use the script in the script folder) or you Docker doesn't have permissions to read that location.

Usually, it is much preferred to run JSShell from linux machines. Hope this helps.
