### ISSUE TITLE
Help me ASAp Please

### ISSUE THREAD

**Issue by amvinayak** [Den1al/JSShell#25]
root@kali:/opt/JSShell# python manage.py web
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    ).get(args.mode)()
  File "manage.py", line 8, in handle_web
    from web import start_api_server
  File "/opt/JSShell/web/__init__.py", line 24
    def start_api_server() -> None:

**Comment by Den1al** [comment]
Can you elaborate on the problem?
